# Generated by Django 4.0 on 2022-02-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGrupo5', '0004_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
